apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: venkatsiddarth/backend_app
        ports:
          - containerPort: 8001
        env:
          - name: POSTGRES_NAME
            value: appDB
          - name: POSTGRES_USER
            value: Siddu
          - name: POSTGRES_PASSWORD
            value: Siddu2002
          - name: POSTGRES_HOST
            value: userdb
          - name: PRODUCTS_REST_HOST
            value: products-rest
          - name: PRODUCTS_GRPC_HOST
            value: products-grpc
          - name: ORDERS_HOST
            value: orders
          - name: CART_HOST
            value: cart

---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30100