# Generated by Django 4.0.4 on 2022-05-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
