# Generated by Django 4.0.4 on 2022-05-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='get_absolute_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='get_image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='get_thumbnail',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
