# Generated by Django 4.0.3 on 2022-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.IntegerField(default=0),
        ),
    ]
