# Generated by Django 4.0.4 on 2022-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_user_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
