# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cart_pb2 as cart__pb2


class cartopsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createcart = channel.unary_unary(
                '/cartops/createcart',
                request_serializer=cart__pb2.createRequest.SerializeToString,
                response_deserializer=cart__pb2.createResponse.FromString,
                )
        self.updatecart = channel.unary_unary(
                '/cartops/updatecart',
                request_serializer=cart__pb2.createRequest.SerializeToString,
                response_deserializer=cart__pb2.updateResponse.FromString,
                )
        self.getCart = channel.unary_unary(
                '/cartops/getCart',
                request_serializer=cart__pb2.getRequest.SerializeToString,
                response_deserializer=cart__pb2.getResponse.FromString,
                )


class cartopsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createcart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updatecart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cartopsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createcart': grpc.unary_unary_rpc_method_handler(
                    servicer.createcart,
                    request_deserializer=cart__pb2.createRequest.FromString,
                    response_serializer=cart__pb2.createResponse.SerializeToString,
            ),
            'updatecart': grpc.unary_unary_rpc_method_handler(
                    servicer.updatecart,
                    request_deserializer=cart__pb2.createRequest.FromString,
                    response_serializer=cart__pb2.updateResponse.SerializeToString,
            ),
            'getCart': grpc.unary_unary_rpc_method_handler(
                    servicer.getCart,
                    request_deserializer=cart__pb2.getRequest.FromString,
                    response_serializer=cart__pb2.getResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cartops', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cartops(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createcart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cartops/createcart',
            cart__pb2.createRequest.SerializeToString,
            cart__pb2.createResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updatecart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cartops/updatecart',
            cart__pb2.createRequest.SerializeToString,
            cart__pb2.updateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cartops/getCart',
            cart__pb2.getRequest.SerializeToString,
            cart__pb2.getResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
