# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\"\x9f\x01\n\x08product_\x12\x0b\n\x03_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10get_absolute_url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\t\x12\x11\n\tget_image\x18\x06 \x01(\t\x12\x15\n\rget_thumbnail\x18\x07 \x01(\t\x12\x10\n\x08quantity\x18\x08 \x01(\x05\"2\n\x04\x63\x61rt\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x18\n\x05items\x18\x02 \x03(\x0b\x32\t.product_\"#\n\rcreateRequest\x12\x12\n\x03req\x18\x01 \x01(\x0b\x32\x05.cart\"$\n\x0e\x63reateResponse\x12\x12\n\x03req\x18\x01 \x01(\x0b\x32\x05.cart\"\"\n\x0eupdateResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\x1e\n\ngetRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"&\n\x0bgetResponse\x12\x17\n\x08response\x18\x01 \x01(\x0b\x32\x05.cart2\x8d\x01\n\x07\x63\x61rtops\x12-\n\ncreatecart\x12\x0e.createRequest\x1a\x0f.createResponse\x12-\n\nupdatecart\x12\x0e.createRequest\x1a\x0f.updateResponse\x12$\n\x07getCart\x12\x0b.getRequest\x1a\x0c.getResponseb\x06proto3')



_PRODUCT_ = DESCRIPTOR.message_types_by_name['product_']
_CART = DESCRIPTOR.message_types_by_name['cart']
_CREATEREQUEST = DESCRIPTOR.message_types_by_name['createRequest']
_CREATERESPONSE = DESCRIPTOR.message_types_by_name['createResponse']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['updateResponse']
_GETREQUEST = DESCRIPTOR.message_types_by_name['getRequest']
_GETRESPONSE = DESCRIPTOR.message_types_by_name['getResponse']
product_ = _reflection.GeneratedProtocolMessageType('product_', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT_,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:product_)
  })
_sym_db.RegisterMessage(product_)

cart = _reflection.GeneratedProtocolMessageType('cart', (_message.Message,), {
  'DESCRIPTOR' : _CART,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:cart)
  })
_sym_db.RegisterMessage(cart)

createRequest = _reflection.GeneratedProtocolMessageType('createRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:createRequest)
  })
_sym_db.RegisterMessage(createRequest)

createResponse = _reflection.GeneratedProtocolMessageType('createResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESPONSE,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:createResponse)
  })
_sym_db.RegisterMessage(createResponse)

updateResponse = _reflection.GeneratedProtocolMessageType('updateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:updateResponse)
  })
_sym_db.RegisterMessage(updateResponse)

getRequest = _reflection.GeneratedProtocolMessageType('getRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:getRequest)
  })
_sym_db.RegisterMessage(getRequest)

getResponse = _reflection.GeneratedProtocolMessageType('getResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'cart_pb2'
  # @@protoc_insertion_point(class_scope:getResponse)
  })
_sym_db.RegisterMessage(getResponse)

_CARTOPS = DESCRIPTOR.services_by_name['cartops']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT_._serialized_start=15
  _PRODUCT_._serialized_end=174
  _CART._serialized_start=176
  _CART._serialized_end=226
  _CREATEREQUEST._serialized_start=228
  _CREATEREQUEST._serialized_end=263
  _CREATERESPONSE._serialized_start=265
  _CREATERESPONSE._serialized_end=301
  _UPDATERESPONSE._serialized_start=303
  _UPDATERESPONSE._serialized_end=337
  _GETREQUEST._serialized_start=339
  _GETREQUEST._serialized_end=369
  _GETRESPONSE._serialized_start=371
  _GETRESPONSE._serialized_end=409
  _CARTOPS._serialized_start=412
  _CARTOPS._serialized_end=553
# @@protoc_insertion_point(module_scope)
