# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x06protos\"\x8b\x01\n\x07product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10get_absolute_url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x11\n\tget_image\x18\x06 \x01(\t\x12\x15\n\rget_thumbnail\x18\x07 \x01(\t\"a\n\x08\x63\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x18\n\x10get_absolute_url\x18\x03 \x01(\t\x12!\n\x08products\x18\x04 \x03(\x0b\x32\x0f.protos.product\"\x17\n\x15latestProductsRequest\":\n\x16latestProductsResponse\x12 \n\x07product\x18\x01 \x03(\x0b\x32\x0f.protos.product\"B\n\x15productDetailsRequest\x12\x14\n\x0c\x63\x61tegoryslug\x18\x01 \x01(\t\x12\x13\n\x0bproductslug\x18\x02 \x01(\t\"7\n\x16productDetailsResponse\x12\x1d\n\x04prod\x18\x01 \x01(\x0b\x32\x0f.protos.product\"/\n\x17\x43\x61tegoryProductsRequest\x12\x14\n\x0c\x63\x61tegoryslug\x18\x01 \x01(\t\"<\n\x18\x43\x61tegoryProductsResponse\x12 \n\x07product\x18\x01 \x03(\x0b\x32\x0f.protos.product\"\x1b\n\rprodIDRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x0eprodIDResponse\x12 \n\x07product\x18\x01 \x03(\x0b\x32\x0f.protos.product\"\x1e\n\rsearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"2\n\x0esearchResponse\x12 \n\x07product\x18\x01 \x03(\x0b\x32\x0f.protos.product2\xf7\x02\n\x0cproductfuncs\x12O\n\x0egetproductlist\x12\x1d.protos.latestProductsRequest\x1a\x1e.protos.latestProductsResponse\x12R\n\x11getproductdetails\x12\x1d.protos.productDetailsRequest\x1a\x1e.protos.productDetailsResponse\x12\x37\n\x06search\x12\x15.protos.searchRequest\x1a\x16.protos.searchResponse\x12\x33\n\x02id\x12\x15.protos.prodIDRequest\x1a\x16.protos.prodIDResponse\x12T\n\x0fgetcategorylist\x12\x1f.protos.CategoryProductsRequest\x1a .protos.CategoryProductsResponseb\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['product']
_CATEGORY = DESCRIPTOR.message_types_by_name['category']
_LATESTPRODUCTSREQUEST = DESCRIPTOR.message_types_by_name['latestProductsRequest']
_LATESTPRODUCTSRESPONSE = DESCRIPTOR.message_types_by_name['latestProductsResponse']
_PRODUCTDETAILSREQUEST = DESCRIPTOR.message_types_by_name['productDetailsRequest']
_PRODUCTDETAILSRESPONSE = DESCRIPTOR.message_types_by_name['productDetailsResponse']
_CATEGORYPRODUCTSREQUEST = DESCRIPTOR.message_types_by_name['CategoryProductsRequest']
_CATEGORYPRODUCTSRESPONSE = DESCRIPTOR.message_types_by_name['CategoryProductsResponse']
_PRODIDREQUEST = DESCRIPTOR.message_types_by_name['prodIDRequest']
_PRODIDRESPONSE = DESCRIPTOR.message_types_by_name['prodIDResponse']
_SEARCHREQUEST = DESCRIPTOR.message_types_by_name['searchRequest']
_SEARCHRESPONSE = DESCRIPTOR.message_types_by_name['searchResponse']
product = _reflection.GeneratedProtocolMessageType('product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.product)
  })
_sym_db.RegisterMessage(product)

category = _reflection.GeneratedProtocolMessageType('category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.category)
  })
_sym_db.RegisterMessage(category)

latestProductsRequest = _reflection.GeneratedProtocolMessageType('latestProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LATESTPRODUCTSREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.latestProductsRequest)
  })
_sym_db.RegisterMessage(latestProductsRequest)

latestProductsResponse = _reflection.GeneratedProtocolMessageType('latestProductsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LATESTPRODUCTSRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.latestProductsResponse)
  })
_sym_db.RegisterMessage(latestProductsResponse)

productDetailsRequest = _reflection.GeneratedProtocolMessageType('productDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDETAILSREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.productDetailsRequest)
  })
_sym_db.RegisterMessage(productDetailsRequest)

productDetailsResponse = _reflection.GeneratedProtocolMessageType('productDetailsResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDETAILSRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.productDetailsResponse)
  })
_sym_db.RegisterMessage(productDetailsResponse)

CategoryProductsRequest = _reflection.GeneratedProtocolMessageType('CategoryProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYPRODUCTSREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.CategoryProductsRequest)
  })
_sym_db.RegisterMessage(CategoryProductsRequest)

CategoryProductsResponse = _reflection.GeneratedProtocolMessageType('CategoryProductsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYPRODUCTSRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.CategoryProductsResponse)
  })
_sym_db.RegisterMessage(CategoryProductsResponse)

prodIDRequest = _reflection.GeneratedProtocolMessageType('prodIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODIDREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.prodIDRequest)
  })
_sym_db.RegisterMessage(prodIDRequest)

prodIDResponse = _reflection.GeneratedProtocolMessageType('prodIDResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODIDRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.prodIDResponse)
  })
_sym_db.RegisterMessage(prodIDResponse)

searchRequest = _reflection.GeneratedProtocolMessageType('searchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.searchRequest)
  })
_sym_db.RegisterMessage(searchRequest)

searchResponse = _reflection.GeneratedProtocolMessageType('searchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:protos.searchResponse)
  })
_sym_db.RegisterMessage(searchResponse)

_PRODUCTFUNCS = DESCRIPTOR.services_by_name['productfuncs']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=27
  _PRODUCT._serialized_end=166
  _CATEGORY._serialized_start=168
  _CATEGORY._serialized_end=265
  _LATESTPRODUCTSREQUEST._serialized_start=267
  _LATESTPRODUCTSREQUEST._serialized_end=290
  _LATESTPRODUCTSRESPONSE._serialized_start=292
  _LATESTPRODUCTSRESPONSE._serialized_end=350
  _PRODUCTDETAILSREQUEST._serialized_start=352
  _PRODUCTDETAILSREQUEST._serialized_end=418
  _PRODUCTDETAILSRESPONSE._serialized_start=420
  _PRODUCTDETAILSRESPONSE._serialized_end=475
  _CATEGORYPRODUCTSREQUEST._serialized_start=477
  _CATEGORYPRODUCTSREQUEST._serialized_end=524
  _CATEGORYPRODUCTSRESPONSE._serialized_start=526
  _CATEGORYPRODUCTSRESPONSE._serialized_end=586
  _PRODIDREQUEST._serialized_start=588
  _PRODIDREQUEST._serialized_end=615
  _PRODIDRESPONSE._serialized_start=617
  _PRODIDRESPONSE._serialized_end=667
  _SEARCHREQUEST._serialized_start=669
  _SEARCHREQUEST._serialized_end=699
  _SEARCHRESPONSE._serialized_start=701
  _SEARCHRESPONSE._serialized_end=751
  _PRODUCTFUNCS._serialized_start=754
  _PRODUCTFUNCS._serialized_end=1129
# @@protoc_insertion_point(module_scope)
